application:
  port: 8000
  host: 0.0.0.0
  service_name: "busted"
  exporter_url: "http://localhost:7281"
database:
  host: "127.0.0.1"
  port: 5432
  username: "test"
  password: "test"
  database_name: "test"
  require_ssl: false